### PR TITLE
UI, continued

### PR DESCRIPTION
**Pull request by JaniAnttonen**
Monster PR to create a basic user flow with our designs.

### CODE REVIEW

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>18aed23</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-vhz1iknnf-equilibriumco.vercel.app'>https://starknet-multisig-vhz1iknnf-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/F63ZX5t2EfZSPu1uLwUCMWniTJgp'>https://vercel.com/equilibriumco/starknet-multisig/F63ZX5t2EfZSPu1uLwUCMWniTJgp</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2256867646)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>c0407d0</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-k5rj7zezk-equilibriumco.vercel.app'>https://starknet-multisig-k5rj7zezk-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/2DfnBXFzK1JK9ezsSDckfsaqjBSX'>https://vercel.com/equilibriumco/starknet-multisig/2DfnBXFzK1JK9ezsSDckfsaqjBSX</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2270366038)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>07a2a27</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-dxe551kbb-equilibriumco.vercel.app'>https://starknet-multisig-dxe551kbb-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/F1Z2HzM85QG7qs2gEwX2bzPLWKNu'>https://vercel.com/equilibriumco/starknet-multisig/F1Z2HzM85QG7qs2gEwX2bzPLWKNu</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2308910910)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>5a76ae7</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-oq38sd8gm-equilibriumco.vercel.app'>https://starknet-multisig-oq38sd8gm-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/ejEt8SWncioMJuEb6DPQrSuuwBqW'>https://vercel.com/equilibriumco/starknet-multisig/ejEt8SWncioMJuEb6DPQrSuuwBqW</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2313508009)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>15c794d</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-b4r02jydz-equilibriumco.vercel.app'>https://starknet-multisig-b4r02jydz-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/BRkYuAtm5Vwr1TWvnRwSyRgU8duh'>https://vercel.com/equilibriumco/starknet-multisig/BRkYuAtm5Vwr1TWvnRwSyRgU8duh</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2395725583)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>f604477</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-lvf1pjisj-equilibriumco.vercel.app'>https://starknet-multisig-lvf1pjisj-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/E5XqEkC8LY4g8XZsjU5MDWdhgMJz'>https://vercel.com/equilibriumco/starknet-multisig/E5XqEkC8LY4g8XZsjU5MDWdhgMJz</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2407867065)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>693df0d</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-jbkhfyo9i-equilibriumco.vercel.app'>https://starknet-multisig-jbkhfyo9i-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/6eUsiEFTGcZGDbqYfrbCXs9Tt4y3'>https://vercel.com/equilibriumco/starknet-multisig/6eUsiEFTGcZGDbqYfrbCXs9Tt4y3</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2428426928)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>10e7d5b</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-hqjr5gaac-equilibriumco.vercel.app'>https://starknet-multisig-hqjr5gaac-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/HXZd5Zoomyg8jTm2pFvzjzcv6EHY'>https://vercel.com/equilibriumco/starknet-multisig/HXZd5Zoomyg8jTm2pFvzjzcv6EHY</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2428863240)

**Comment by microbecode** [comment]
This looks great!
Played around a bit and found some issues. Unsure how ready this should be currently, so let's discuss when you get back from holidays.

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>c11cb1c</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-94htbf8eq-equilibriumco.vercel.app'>https://starknet-multisig-94htbf8eq-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/CMtXn4bJWBYga7CxC8rHEbohZeKD'>https://vercel.com/equilibriumco/starknet-multisig/CMtXn4bJWBYga7CxC8rHEbohZeKD</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2508674523)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>692d435</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-ax3lq0gyz-equilibriumco.vercel.app'>https://starknet-multisig-ax3lq0gyz-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/HftQJQoJieU49WGDhEsFpne6iGrT'>https://vercel.com/equilibriumco/starknet-multisig/HftQJQoJieU49WGDhEsFpne6iGrT</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2535825876)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>f80abbf</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-m5t9ms3ag-equilibriumco.vercel.app'>https://starknet-multisig-m5t9ms3ag-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/DdnNQED8UW8sxVTvjrKBPC9Q6uYZ'>https://vercel.com/equilibriumco/starknet-multisig/DdnNQED8UW8sxVTvjrKBPC9Q6uYZ</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2575957474)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>b55b257</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-3cazp7clu-equilibriumco.vercel.app'>https://starknet-multisig-3cazp7clu-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/CWyhAusEKDsebDF1eQoLQk7kSzEN'>https://vercel.com/equilibriumco/starknet-multisig/CWyhAusEKDsebDF1eQoLQk7kSzEN</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2589068984)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>53c6b07</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-9j55ymlf2-equilibriumco.vercel.app'>https://starknet-multisig-9j55ymlf2-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/BzjBBuXMyE55fkQscCTyXgyjN17S'>https://vercel.com/equilibriumco/starknet-multisig/BzjBBuXMyE55fkQscCTyXgyjN17S</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2589105775)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>afafc50</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-7evmnd13n-equilibriumco.vercel.app'>https://starknet-multisig-7evmnd13n-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/AcqSZYB1iv6rawrei6Ws6M27Rci2'>https://vercel.com/equilibriumco/starknet-multisig/AcqSZYB1iv6rawrei6Ws6M27Rci2</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2589177321)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>93f604d</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-nfu3o0j8g-equilibriumco.vercel.app'>https://starknet-multisig-nfu3o0j8g-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/nUoRzmvnix6whJKecLK4syzp3yGS'>https://vercel.com/equilibriumco/starknet-multisig/nUoRzmvnix6whJKecLK4syzp3yGS</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2589520427)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>1ea813a</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-8gptyuh92-equilibriumco.vercel.app'>https://starknet-multisig-8gptyuh92-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/EUQg799qACNwruvApDS4qTg4iqWc'>https://vercel.com/equilibriumco/starknet-multisig/EUQg799qACNwruvApDS4qTg4iqWc</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2589896948)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>dbb32a6</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-n80zuigfi-equilibriumco.vercel.app'>https://starknet-multisig-n80zuigfi-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/8m7idMobZhvDJaWuFf1yxVZXapah'>https://vercel.com/equilibriumco/starknet-multisig/8m7idMobZhvDJaWuFf1yxVZXapah</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2596151340)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>0c4a89c</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-l6t44cozv-equilibriumco.vercel.app'>https://starknet-multisig-l6t44cozv-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/FFL42hdrMaBj6z6PFvxdYXzB4XGJ'>https://vercel.com/equilibriumco/starknet-multisig/FFL42hdrMaBj6z6PFvxdYXzB4XGJ</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2610652045)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>4b0dd67</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-rfo9dpjj9-equilibriumco.vercel.app'>https://starknet-multisig-rfo9dpjj9-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/BE1BdyfLZ6xkmzqVXnXBjvHMBvLx'>https://vercel.com/equilibriumco/starknet-multisig/BE1BdyfLZ6xkmzqVXnXBjvHMBvLx</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2611022631)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>0fb7c95</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-g8kjxyy1x-equilibriumco.vercel.app'>https://starknet-multisig-g8kjxyy1x-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/3xemgCdn4tXf1zhwNVdB5sgJTuvB'>https://vercel.com/equilibriumco/starknet-multisig/3xemgCdn4tXf1zhwNVdB5sgJTuvB</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2657429383)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>0bdd85a</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-krz63oc4e-equilibriumco.vercel.app'>https://starknet-multisig-krz63oc4e-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/Gxr4JDdJqoroHioNiwFidtUg8hpc'>https://vercel.com/equilibriumco/starknet-multisig/Gxr4JDdJqoroHioNiwFidtUg8hpc</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2670155867)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>f804eb4</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-hnglfst5x-equilibriumco.vercel.app'>https://starknet-multisig-hnglfst5x-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/EuUEW5TK8EkJUxEiiS4UK4nGqPg6'>https://vercel.com/equilibriumco/starknet-multisig/EuUEW5TK8EkJUxEiiS4UK4nGqPg6</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2697337959)

**Comment by JaniAnttonen** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>114b499</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-a3gurowgx-equilibriumco.vercel.app'>https://starknet-multisig-a3gurowgx-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/GPeAFRaMuwnxHKitVbccLobbpQCQ'>https://vercel.com/equilibriumco/starknet-multisig/GPeAFRaMuwnxHKitVbccLobbpQCQ</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2704089483)

**Pull request closed without merging**
